#!/usr/bin/python
import requests
res = requests.get('http://posudacenter.ru/')
res.raise_for_status()
playFile = open('posuda.html','wb')
for chunk in res.iter_content(100000):
    playFile.write(chunk)
playFile.close()




