#!/ usr/bin/python

#step1 write pattern
#step2 count how many catalogs we have
#step3 write id of each catalog in column in csv file from 1 to 8 (according quanitiy)
#step4 also fill in "Active" (0/1) Column from 1 to 8 (accordint quantity)
#step5 fill "Name" column with catalog names extracted from web
#looks like cat id must start from 4 or higher i choose 11
import bs4, csv

soup=bs4.BeautifulSoup(open('posuda.html'),'lxml')                                        #open prepared file
Elems=soup.select('.header-toolbar-navigation__item .header-toolbar-navigation__link')    #find main catalogs

#step1 write presta catalogs pattern in csv file
presta_cat_pattern = "ID;Active (0/1);Name *;Parent category;Root category (0/1);Description;Meta title;Meta keywords;Meta description;URL rewritten;Image URL\n"
f=open('parsed.csv','wt')
f.write(presta_cat_pattern)

#step2 count how many catalogs we have
Elems_quantity=len(Elems)                  #count list of extracted catalogs
print('Catalogs quantity = ',Elems_quantity)

#step3 write id of each catalog in column in csv file from 1 to 8 (according quanitiy)
# ID; ACTIVE; NAME; Parent category; etc
num=1                                       #initialization of helper counter
id=11
for i in range(Elems_quantity):             #start iterato over all found elements in html file 
    if Elems_quantity > (num-1):            #condition for ID writer
        f.write(str(id))                         #column  ID (ID writer) must be string
        id=int(id)
        num=int(num)+1                      #increment helper counter
        f.write(';1;')                      #write in column Active 1 because i think all cats will be active
        f.write(Elems[i].text)              #write categories names
        f.write(';Home;')                   #write text "Parent category"
        f.write('0;')
        f.write('Description;')
        f.write('\n')
f.close()                                   #close file
print('cats written in file =',f.name)

