if(window.G)throw Error('Global namespace "G" is occupied!');window.G={};(function(){var a=window.navigator.userAgent.toLowerCase(),b=(a.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/)||[0,"0"])[1],d=/msie/.test(a)&&!/opera/.test(a),c=/mozilla/.test(a)&&!/(compatible|webkit)/.test(a),e=/opera/.test(a);/webkit/.test(a);var g=/safari/.test(a)&&!/chrome/.test(a),f=/chrome/.test(a),a=[];d?(b=parseFloat(b),a.push("ie","ie"+b),(7===b||8===b)&&a.push("ie7-8")):c?a.push("firefox"):g?a.push("safari"):f?a.push("chrome"):e&&a.push("opera");jQuery(document.documentElement).addClass(a.join(" "))})();!function(a,b,d){var c,e;function g(){return"function"!=typeof b.createElement?b.createElement(arguments[0]):Q?b.createElementNS.call(b,"http://www.w3.org/2000/svg",arguments[0]):b.createElement.apply(b,arguments)}function f(a){return a.replace(/([a-z])-([a-z])/g,function(a,c,b){return c+b.toUpperCase()}).replace(/^-/,"")}function j(a,c){return function(){return a.apply(c,arguments)}}function h(a){return a.replace(/([A-Z])/g,function(a,c){return"-"+c.toLowerCase()}).replace(/^ms-/,"-ms-")}function m(a,
c,d,e){var f,h,l,j,o=g("div"),r,m=b.body;r=(m||(m=g(Q?"svg":"body"),m.fake=!0),m);if(parseInt(d,10))for(;d--;)l=g("div"),l.id=e?e[d]:"modernizr"+(d+1),o.appendChild(l);return f=g("style"),f.type="text/css",f.id="smodernizr",(r.fake?r:o).appendChild(f),r.appendChild(o),f.styleSheet?f.styleSheet.cssText=a:f.appendChild(b.createTextNode(a)),o.id="modernizr",r.fake&&(r.style.background="",r.style.overflow="hidden",j=y.style.overflow,y.style.overflow="hidden",y.appendChild(r)),h=c(o,a),r.fake?(r.parentNode.removeChild(r),
y.style.overflow=j):o.parentNode.removeChild(o),!!h}function p(c,b){var e=c.length;if("CSS"in a&&"supports"in a.CSS){for(;e--;)if(a.CSS.supports(h(c[e]),b))return!0;return!1}if("CSSSupportsRule"in a){for(var f=[];e--;)f.push("("+h(c[e])+":"+b+")");return f=f.join(" or "),m("@supports ("+f+") { #modernizr { position: absolute; } }",function(c){if("getComputedStyle"in a){var c=getComputedStyle.call(a,c,null),b=a.console;null!==c?c=c.getPropertyValue("position"):b&&b[b.error?"error":"log"].call(b,"getComputedStyle returning null, its possible modernizr test results are inaccurate")}else c=
c.currentStyle&&c.currentStyle.position;return"absolute"==c})}return d}function u(a,b,h,l){function j(){r&&(delete c,delete e)}if(l="undefined"===typeof l?!1:l,"undefined"!==typeof h){var o=p(a,h);if("undefined"!==typeof o)return o}for(var r,m,t,y,o=["modernizr","tspan","samp"];!c&&o.length;)r=!0,e=g(o.shift()),c=e.style;for(m=a.length,o=0;m>o;o++)if(t=a[o],y=c[t],!!~(""+t).indexOf("-")&&(t=f(t)),c[t]!==d){if(l||"undefined"===typeof h)return j(),"pfx"==b?t:!0;try{c[t]=h}catch(w){}if(c[t]!=y)return j(),
"pfx"==b?t:!0}return j(),!1}function o(a,c,b,d,e){var f=a.charAt(0).toUpperCase()+a.slice(1),h=(a+" "+F.join(f+" ")+f).split(" "),l;if("string"===typeof c||"undefined"===typeof c)l=u(h,c,d,e);else{h=(a+" "+W.join(f+" ")+f).split(" ");a:{var a=h,g;for(g in a)if(a[g]in c){c=!1===b?a[g]:(l=c[a[g]],"function"===typeof l?j(l,b||c):l);break a}c=!1}l=c}return l}function r(a,c,b){return o(a,d,d,c,b)}var s=[],l=[],t={_version:"3.5.0",_config:{classPrefix:"",enableClasses:!0,enableJSClass:!0,usePrefixes:!0},
_q:[],on:function(a,c){var b=this;setTimeout(function(){c(b[a])},0)},addTest:function(a,c,b){l.push({name:a,fn:c,options:b})},addAsyncTest:function(a){l.push({name:null,fn:a})}},w=function(){};w.prototype=t;w=new w;var y=b.documentElement,Q="svg"===y.nodeName.toLowerCase(),I=t._config.usePrefixes?["","-webkit-","-moz-","-o-","-ms-"]:["",""];t._prefixes=I;w.addTest("csspositionsticky",function(){var a=g("a").style;return a.cssText="position:"+I.join("sticky;position:").slice(0,-9),-1!==a.position.indexOf("sticky")});
var F=t._config.usePrefixes?["Moz","O","ms","Webkit"]:[];t._cssomPrefixes=F;var W=t._config.usePrefixes?["moz","o","ms","webkit"]:[];t._domPrefixes=W;var D=g("modernizr");w._q.push(function(){delete D});c=D.style;e=void 0;w._q.unshift(function(){delete c});t.testAllProps=o;t.testAllProps=r;w.addTest("flexbox",r("flexBasis","1px",!0));(function(){var a,c,b,d,e,f,h;for(h in l)if(l.hasOwnProperty(h)){if(a=[],c=l[h],c.name&&(a.push(c.name.toLowerCase()),c.options&&c.options.aliases&&c.options.aliases.length))for(b=
0;b<c.options.aliases.length;b++)a.push(c.options.aliases[b].toLowerCase());for(b="function"===typeof c.fn?c.fn():c.fn,d=0;d<a.length;d++)e=a[d],f=e.split("."),1===f.length?w[f[0]]=b:(!w[f[0]]||w[f[0]]instanceof Boolean||(w[f[0]]=new Boolean(w[f[0]])),w[f[0]][f[1]]=b),s.push((b?"":"no-")+f.join("-"))}})();(function(a){var c=y.className,b=w._config.classPrefix||"";if(Q&&(c=c.baseVal),w._config.enableJSClass)c=c.replace(RegExp("(^|\\s)"+b+"no-js(\\s|$)"),"$1"+b+"js$2");w._config.enableClasses&&(c+=
" "+b+a.join(" "+b),Q?y.className.baseVal=c:y.className=c)})(s);delete t.addTest;delete t.addAsyncTest;for(t=0;t<w._q.length;t++)w._q[t]();a.Modernizr=w}(window,document);G.f=function(a){throw a;};G.j=void 0;G.l=!0;G.m=null;G.n=!1;G.ca=function(){return function(a){return a}};G.o=function(){return function(){}};G.ea=function(a){return function(b){this[a]=b}};G.p=function(a){return function(){return this[a]}};G.r=function(a){return function(){return a}};G.ha=function(a){return function(){return G.ja[a].apply(this,arguments)}};G.ka=function(a,b,d){return a.call.apply(a.bind,arguments)};
G.la=function(a,b,d){a||(0,G.f)(Error());if(2<arguments.length){var c=Array.prototype.slice.call(arguments,2);return function(){var d=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(d,c);return a.apply(b,d)}}return function(){return a.apply(b,arguments)}};G.u=function(a,b,d){G.u=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?G.ka:G.la;return G.u.apply(G.m,arguments)};
G.w=function(a,b){function d(){}d.prototype=b.prototype;a.W=b.prototype;a.prototype=new d;a.prototype.constructor=a};G.x=function(){this.I=jQuery({})};G.z=function(a,b,d,c){a===G.m&&(0,G.f)(Error("Popup root must be not null"));this.l=a;this.Jb=b||G.m;this.w=this.l.find(".popup_close");this.u=this.o=G.m;this.v=jQuery(d||document);this.m=c||G.m;this.h=jQuery({});this.i=this.l.hasClass("not_display")||!this.l.is(":visible");this.k=G.n;this.ea=jQuery(window);this.C()};
G.na=function(a){a.Jb&&a.Jb.click(function(b){a.toggle();b.preventDefault()});a.w.click(function(){a.close()});jQuery(document).keyup(function(b){b.which===G.pa&&a.close()});a.v.click(function(b){var d=1===b.which||0===b.which,c=a.l.is(b.target)||0<a.l.has(b.target).size(),e=G.n;a.Jb&&(e=a.Jb.is(b.target)||0<a.Jb.has(b.target).size());b=!c&&!e||b.target===a.v[0];d&&b&&a.close()});a.ea.resize(function(){a.i||(0,G.qa)(a)})};
G.qa=function(a){var b,d;if(a.o&&a.u){var c=a.u.offset();b=a.l;d=a.o.offset();var e=b.offset();b=d.left-e.left;d=d.top-e.top;b=c.left-b;c=c.top-d;d=a.l.offsetParent().offset();a.l.css({left:b-d.left,top:c-d.top})}};
G.ra=function(a,b){if(a[0]["gos.GameSelect"]){var d=a[0]["gos.GameSelect"];b&&(0,G.sa)(d);return d}a[0]["gos.GameSelect"]=this;this.I=jQuery({});this.l=a;this.l.length&&(this.h=this.l.find(".game_select_popup"),this.Nk=this.h.find("li"),this.i=this.l.find(".game_select_popup_opener"),new G.z(this.h,this.i))};
G.sa=function(a){a.h.on("click","a",(0,G.u)(function(a){a.preventDefault();a=jQuery(a.currentTarget);this.l.find(".game_select_popup_opener").html(a.html());this.Nk.removeClass("selected");a.closest("li").addClass("selected");this.I.trigger("change",{abbr:a.data("abbr")})},a))};G.ja=[];G.ta=this;Math.floor(2147483648*Math.random()).toString(36);G.x.prototype.addEventListener=function(a,b,d){this.I.bind(a,jQuery.proxy(b,d||this.I))};G.x.prototype.removeEventListener=(0,G.ha)(8);G.t=G.z.prototype;
G.t.nb=(0,G.ha)(9);G.t.ag=(0,G.ha)(3);G.t.toggle=function(){this.i?this.open():this.close()};
G.t.open=function(){var a=this;this.i&&!this.k&&(this.m?(this.k=G.l,this.l.css("opacity",0).removeClass("not_display"),(0,G.qa)(this),this.h.trigger("before-open"),this.l.animate({opacity:1},this.m,"linear",function(){a.i=G.n;a.k=G.n;a.h.trigger("after-open")})):(this.l.addClass("invisible").removeClass("not_display"),(0,G.qa)(this),this.h.trigger("before-open"),this.i=G.n,this.l.removeClass("invisible"),this.h.trigger("after-open")))};
G.t.close=function(){var a=this;!this.i&&!this.k&&(this.h.trigger("before-close"),this.m?(this.k=G.l,this.l.animate({opacity:0},this.m,"linear",function(){a.l.addClass("not_display");a.i=G.l;a.k=G.n;a.h.trigger("after-close")})):(this.i=G.l,this.l.addClass("not_display"),this.h.trigger("after-close")))};G.t.addEventListener=function(a,b){this.h.bind(a,b)};G.t.removeEventListener=(0,G.ha)(7);
G.t.C=function(){if(this.Jb){var a=this.l.find(".popup_positioner"),b=this.Jb.find(".popup_positioner");a.size()&&(this.o=a,this.u=b.size()?b:this.Jb)}(0,G.na)(this)};(0,G.w)(G.ra,G.x);jQuery(function(){jQuery(".game_select").each(function(a,b){new G.ra(jQuery(b))})});